### PR TITLE
Fix issue when using batch operations on different classes with the same table name

### LINKED ISSUE #47: batchGet is returning same instance objects though the input has different instances
Please refer to this file. Thanks

[Issue.txt](https://github.com/awslabs/dynamodb-data-mapper-js/files/1963128/Issue.txt)

### PR DESCRIPTION
**Pull request by ofekray**
Resolves #47 

*Description of changes:*
In DataMapper.ts itemIdentifier function always returned ":" as no items were pushed to the keyAttributes array.
This caused problems with batch operations of different models using the same table name.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: packages/dynamodb-data-mapper/src/DataMapper.ts [hunk 1]
```diff
@@ -1121,12 +1121,13 @@ export class DataMapper {
         return getTableName(item, this.tableNamePrefix);
     }
 
-    private async *mapGetBatch<T extends StringToAnyObjectMap>(
+    private async mapGetBatch<T extends StringToAnyObjectMap>(
```
Comment (jeskew) [inline packages/dynamodb-data-mapper/src/DataMapper.ts]: Is this change necessary? Seems unrelated to the bugfix on line 1342

Comment (ofekray) [reply packages/dynamodb-data-mapper/src/DataMapper.ts]: You are right this change is not necessary.
I reverted it.
